# Generated by Django 3.2 on 2021-05-02 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni_kategorie', models.CharField(help_text='Zadejte název kategorie o maximální délce 25 znaků; název musí být jedinečný', max_length=25, unique=True, verbose_name='Označení kategorie')),
                ('nazev_kategorie', models.CharField(blank=True, choices=[('postele', 'Postele'), ('stoly', 'Stoly'), ('židle', 'Židle'), ('pohovky', 'Pohovky'), ('venkovní nábytek', 'Venkovní nábytek'), ('komody', 'Komody'), ('šatní skříně', 'Šatní skříně')], help_text='Vyberte kategorii', max_length=25, verbose_name='Název kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie produktů',
                'verbose_name_plural': 'Kategorie produktů',
                'ordering': ['oznaceni_kategorie'],
            },
        ),
        migrations.CreateModel(
            name='Kolekce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_kolekce', models.CharField(help_text='Zadejte název kolekce o maximální délce 50 znaků; název musí být jedinečný', max_length=50, unique=True, verbose_name='Název kolekce')),
                ('datum_vydani', models.DateField(help_text='Zadejte datum vydání kolekce', verbose_name='Datum vydání kolekce')),
            ],
            options={
                'verbose_name': 'Kolekce produktů',
                'verbose_name_plural': 'Kolekce produktů',
                'ordering': ['nazev_kolekce'],
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název produktu o maximální délce 50 znaků; název musí být jedinečný', max_length=50, unique=True, verbose_name='Název prodkutu')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis produktu')),
                ('cena', models.IntegerField(help_text='Zadejte cenu produktu vyšší než 1', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cena produktu')),
                ('pocet_ks', models.IntegerField(help_text='Zadejte počet kusů na skladě', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Počet kusů na skladě')),
                ('foto', models.ImageField(blank=True, upload_to='produkty', verbose_name='Fotka produktu')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='katalog.kategorie')),
                ('kolekce', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='katalog.kolekce')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['-cena', 'nazev'],
            },
        ),
    ]
