# Generated by Django 3.2 on 2021-05-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorie',
            options={'ordering': ['nazev_kategorie'], 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='kolekce',
            options={'ordering': ['nazev_kolekce'], 'verbose_name': 'Kolekce', 'verbose_name_plural': 'Kolekce'},
        ),
        migrations.RemoveField(
            model_name='kategorie',
            name='oznaceni_kategorie',
        ),
        migrations.AlterField(
            model_name='kategorie',
            name='nazev_kategorie',
            field=models.CharField(help_text='Zadejte název kategorie o maximální délce 25 znaků; název musí být jedinečný', max_length=25, unique=True, verbose_name='Název kategorie'),
        ),
    ]
