# Generated by Django 3.2 on 2021-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20210503_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='nazev_kategorie',
            field=models.CharField(help_text='Zadejte název kategorie o maximální délce 50 znaků; název musí být jedinečný', max_length=50, unique=True, verbose_name='Název kategorie'),
        ),
    ]
